### ISSUE TITLE
Pusher Combine

### ISSUE THREAD

**Issue by neumeyerc** [haarnoja/softqlearning#17]
Hi!

Thanks a lot making the code available!

One question: The paper discusses composing Q-functions by averaging them w.r.t the number of sub-tasks (equation 6). The pusher example (pusher_combine) appears to be adding the Q-functions with no averaging happening. Is this correct or did I miss anything?

**Comment by haarnoja** [comment]
Thanks for the question! In the paper, we chose to use the average since it made the math a bit simpler, but in practice the magnitude of the Q-functions is anyway arbitrary, so we might want to scale them to hit the right balance between the different objectives. There is no particular reason why we chose to multiply the average by 2 (= simply sum up the Q-functions), and you might want to try different scales anyway, or perhaps use a weighted combination. Hope this clarifies!

**Comment by neumeyerc** [comment]
Thanks!
